<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 14/09/2016
 * Time: 08:05 PM
 */ ?>
<div class="section no-pad-bot scrollspy ">
    <div class="container">


        <div class="row">
            <div class="valign-wrapper">
            <form class="col s4 m4 l4 center-align">
                <div class="row">
                    <div class="input-field">
                        <input id="first_name" type="text" class="validate">
                        <label for="first_name">Usuario</label>
                    </div>
                    <div class="input-field">
                        <input id="last_name" type="text" class="validate">
                        <label for="last_name">Password</label>
                    </div>
                </div>
                </div>
            </form>
        </div>
    </div>
</div>