<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 01/10/2016
 * Time: 04:00 PM
 */ ?>
<div class="container">
    <div class="row">
        <h3><?php echo $title; ?></h3>
    </div>
    <div class="row">
        <?php $cards = array(
            (object)array("nome" => "Informazione personali", "color" => "green", "descrizione" =>
                "Aggiungere, modificare, mostrare e elimininare informazione personali", "url" => ""),
            (object)array("nome" => "Slides", "color" => "blue", "descrizione" =>
                "Aggiungere, modificare, mostrare e elimininare slides", "url" => "/slides/"),
            (object)array("nome" => "Lavori", "color" => "orange", "descrizione" =>
                "Aggiungere, modificare, mostrare e elimininare lavori", "url" => "/lavori/mostrare"),
            (object)array("nome" => "Servizi", "color" => "purple", "descrizione" =>
                "Aggiungere, modificare, mostrare e elimininare servizi", "url" => "/servizis/mostrare"),
            (object)array("nome" => "Prodotti", "color" => "purple", "descrizione" =>
                "Aggiungere, modificare, mostrare e elimininare prodotti", "url" => "/prodotti/mostrare")

        ); ?>
        <?php foreach ($cards as $card): ?>
            <div class=" col s12 m6 l4 ">
                <div class="card black hoverable">

                    <div class="card-content">
                        <span class="card-title yellow-text ">
                            <?php echo $card->nome; ?>
                        </span>
                        <p class=" white-text"> <?php echo $card->descrizione; ?></p>
                        <div class=" right-align">
                        <a href="<?php echo $card->url;?>" class="waves-effect waves-light yellow
                        btn-floating">
                            <i class=" black-text material-icons">settings</i>
                        </a>
                        </div>
                    </div>

                </div>
            </div>
        <?php endforeach; ?>

    </div>
</div>
