<div id="intro" class="  section scrollspy">
    <div class="container">

        <div class="row">

            <div class="col s12 m12 l12">
                <h3>¿Chi siamo?</h3>
                <div class="card-panel grey lighten-3">
                    <p class="flow-text ">

                        PRO-PAINTER <br>
                        E un'impresa giovane, ma e anche il risultato di molti anni di esperienza nel campo delle
                        vernici, delle
                        decorazioni, della progettazione e realizzazione di stand e show-room.
                        Dedichiamo la massima attenzione ai dettagli, fin dai lavori più semplici a quelli più
                        complessi. Non abbiamo fretta e
                        siamo soddisfatti solo quando ogni lavori si consegna al cliente al 100%
                        Comunque, garantendo gran professionalità e serietà nei lavori, sappiamo anche che riusciamo a
                        offrire un rapporto
                        qualità prezzo molto vantaggioso, cercando sempre di adeguarci alle necessita e possibilità del
                        cliente.
                        Ci accompagna la passione in quello che facciamo, per questo siamo orgogliosi della nostra
                        impresa.


                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <blockquote>
                <h4>Prodotti che utilizziamo</h4>
            </blockquote>
        </div>
        <div class="row">

            <?php foreach($prodotti as $prodotto):?>
            <div class="card-panel col s12 m3 l3 ">
                <a href="<?php echo $prodotto->url;?>" target="_blank" title="Visitare il sitio">
                <?php echo Html::img("prodotti/".Utils::slug($prodotto->nome)."/".
                    $prodotto->getImmagini($prodotto->id)->nombre,$prodotto->nome,
                    "class=' center-align responsive-img'");?>
                </a>
            </div>
            <?php endforeach;?>
        </div>


    </div>
</div>
<div class="row">

</div>
<div class="row">

</div>
<div class="row">

</div>



