
<div class="slider">

    <ul class="slides">
        <?php foreach($slides as $slide):?>
        <li>
           <?php echo Html::img("slides/".
               $slide->nome.".".$slide->getExtension($slide->id)->extension,$slide->nome,"class=' 
               responsive-img'");?>

            <div class="caption left-align carousel-content ">
                <h3><?php echo $slide->nome;?></h3>
                <h5 class="light grey-text text-lighten-3"><?php echo $slide->descrizione;?></h5>
            </div>
        </li>
        <?php endforeach;?>


    </ul>
</div>


