
<div class="slider">

    <ul class="slides">
        <?php foreach($slides as $slide):?>
        <li>
           <?php echo Html::img($slide->img,$slide->titulo,"class='responsive-img'");?>

            <div class="caption <?php echo $slide->direccion;?> carousel-content ">
                <h3><?php echo $slide->titulo;?></h3>
                <h5 class="light grey-text text-lighten-3"><?php echo $slide->mensaje;?></h5>
            </div>
        </li>
        <?php endforeach;?>


    </ul>
</div>


