<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 22/09/2016
 * Time: 07:12 PM
 */

?>
<div class="section scrollspy" id="lavori">
    <div class="container">

        <div class="row">
            <blockquote>
                <h4><?php echo $title; ?></h4>
            </blockquote>
        </div>
        <div class="row">
            <?php View::content() ?>
        </div>


        <div class="row">
            <?php echo Form::open(); ?>
            <div class="input-field col s12 m12 l12">
                <?php echo Form::text("lavori.nome", "class='validate' required"); ?>
                <label for="disabled">Nome del lavori</label>
            </div>

        </div>
        <div class="row">
            <div class="input-field col s12 m12 l12">
                <?php echo Form::textarea("lavori.descrizione", "class='materialize-textarea validate' required"); ?>
                <label for="disabled">Descrizione del lavori</label>
            </div>

        </div>

<!--        <div class="row">-->
<!--            <div class="input-field col s12 m12 l12">-->
<!---->
<!--                <div class="chips chips-placeholder"></div>-->
<!--            </div>-->
<!---->
<!--        </div>-->
<!--        --><?php //echo Form::hidden("lavori.servizi_tags"); ?>

        <div class="row center-align">
            <a href='<?php echo PUBLIC_PATH . $controller_name . "/mostrare" ?>'
               class=" btn-large btn-flat">Annullare</a>
            <?php echo Form::submit("Aggiungere", "class='waves-effect waves-light btn-block  
            btn-large yellow black-text'"); ?>
        </div>

        <?php echo Form::close(); ?>
    </div>
</div>
