<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 15/09/2016
 * Time: 02:07 PM
 */
View::content()
?>
<div class="section scrollspy" id="lavori">
    <div class="container">

        <div class="master">

            <div class="row">
                <h3 class=" "><?php echo $title;?></h3>

            </div>

            <div class="row">

                <?php foreach ($lavori as $lavoro): ?>

                    <div class=" col s12 m4 l4 ">

                        <div class="card lavoro-card hoverable">

                            <div class=" card-image   ">

                                <?php $img_principale = $lavoro->getImmaginePrincipale($lavoro->id); ?>
                                <?php if ($img_principale->nombre != null): ?>
                                    <?php echo Html::img("lavori/" .Utils::slug($lavoro->nome). "/" . $img_principale->nombre
                                        , "", "class=' servizio  center-align responsive-img'"); ?>
                                <?php else: ?>
                                    <?php echo Html::img("img-not-found.jpg", "", "class='servizio responsive-img'"); ?>
                                <?php endif; ?>
                            </div>
                            <div class="card-content black  ">
                                
                            <span class=" card-title  white-text">
                                <?php echo $lavoro->nome; ?>
                                 </span>
                                <a href="#" onclick="openDetails(<?php echo $lavoro->id; ?>,event)"
                                   class="btn-floating waves-effect waves-light darken-1 yellow right">
                                    <i class="material-icons right">add</i>
                                </a>


                            </div>

                        </div>
                    </div>

                <?php endforeach; ?>


            </div>
        </div>

        <div class="row detail">
            <a id="btn-back" href="#" class="left hidden btn btn-floating blue"><i
                    class="material-icons" title="Ritorno">keyboard_backspace</i></a>
            <?php foreach ($lavori as $lavoro): ?>
                <div class="hidden" id="detail-<?php echo $lavoro->id; ?>">
                    <h4 class="center center-align"><?php echo $lavoro->nome; ?></h4>

                    <p class="flow-text"><?php echo $lavoro->descrizione; ?></p>
                    <h5>Immagini</h5>
                    <?php foreach ($immagini = $lavoro->getImmagini($lavoro->id) as $item): ?>
                        <div class="col s12 m3 l3">
                            <div class="card-panel center">
                                <a rel="<?php echo $lavoro->nome;?>" class="swipebox" title="<?php echo
                                    '<b>'.$item->nome.'</b><br>'.$item->descrizione?>"
                                   href="<?php echo PUBLIC_PATH . "img/lavori/" . Utils::slug($lavoro->nome)
                                       . "/" . $item->nombre ?>">
                                    <?php echo Html::img("lavori/" . Utils::slug($lavoro->nome) . "/" . $item->nombre
                                        , "", "class='  responsive-img'"); ?>

                                </a>

                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <input type="hidden" id="hdn_detail_id">
    </div>
</div>