<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 22/09/2016
 * Time: 07:12 PM
 */

?>
<div class="section scrollspy" id="lavori">
    <div class="container">
        <div class="row">
            <h3><?php echo $title; ?></h3>
        </div>
        <!--        <div class="row">-->
        <!--            --><?php //View::content() ?>
        <!--        </div>-->
        <div class="row">
            <?php echo Form::open(); ?>
            <div class="input-field col s12 m7 l7">
                <?php echo Form::text("lavori.nome", "class='validate'"); ?>
                <label for="lavori_nome">Nome del lavorio</label>
            </div>
            <div class="input-field col s12 m5 l5">
                <?php echo Form::dbSelect("lavori.statos_lavori_id", "nome", array("statos_lavori", "getStatos"),
                    "Seleccione","class=''")?>
                <label for="lavori_stato">Stato del lavoro</label>

            </div>

        </div>
        <div class="row">
            <div class="input-field col s12 m12 l12">
                <?php echo Form::textarea("lavori.descrizione", "class='materialize-textarea validate'"); ?>
                <label for="lavori_descrizione">Descrizione del lavorio</label>
            </div>

        </div>
        <div class="row center-align">
            <a href='<?php echo PUBLIC_PATH . $controller_name . "/mostrare" ?>'
               class=" btn-large btn-flat">Annullare</a>
            <?php echo Form::submit("Modificare", "class='waves-effect waves-light btn-block  
            btn-large yellow black-text'"); ?>
        </div>
        <?php echo Form::hidden("lavori.id", FALSE, $lavori->id); ?>
        <?php echo Form::close(); ?>

    </div>
</div>
