
<div class="section scrollspy" id="slides">
    <div class="container">
        <div class="row">
            <?php View::content();?>
        </div>
        <div class="row">
            <h3><?php echo $title; ?></h3>
        </div>

        <div class="row">
            <?php echo Html::link("slides/aggiungere", "<i class='material-icons'>add</i>", "class='btn-floating 
        light-green darken-1 right' title='Aggiungere un slide'"); ?>
        </div>
        <div class="row">

            <?php if (count($slides) < 0 || $slides ==null): ?>
            <p class="flow-text red-text">
                Nessun risultato da mostrare</p>
            <?php else: ?>
            <table class="highlight">
                <thead>
                <tr>
                    <th data-field="id">#</th>
                    <th data-field="nome">Nome</th>
                    <th data-field="descrizione">Descrizione</th>
<!--                    <th data-field="numero_di_immagini">N° immagini</th>-->
                    <th data-field="azioni">Azioni</th>
                </tr>
                </thead>

                <tbody>

                    <?php $i=1;foreach ($slides as $slide): ?>
                        <tr>
                            <td><?php echo "<b>".$i."</b>"; ?></td>
                            <td><?php echo $slide->nome; ?></td>
                            <td>
                                <?php if (strlen($slide->descrizione) > 130): ?>
                                    <?php echo substr($slide->descrizione, 0, 129) ?>&nbsp;<strong>...</strong>
                                <?php else: ?>
                                    <?php echo $slide->descrizione ?>
                                <?php endif ?>
                            </td>
<!--                            <td>-->
<!--                                --><?php //echo count($immagini_slides);?>
<!--                            </td>-->
                            <td>
                                <?php echo Html::link("immagini_slides/mostrare/" .
                                    $slide->id, "<i class='material-icons'>queue</i>",
                                    "class='btn-floating purple' title='Aggiungere immagini'");?>
                                <?php echo Html::link("slides/modificare/" .
                                    $slide->id, "<i class='material-icons'>edit</i>",
                                    "class='btn-floating blue' title='Modifica'");?>
                                <a href="#modal-<?php echo $slide->id?>"
                                   class='modal-trigger btn-floating red' title='Eliminare slide?'>
                                    <i class='material-icons'>delete</i>
                                </a>

                            </td>
                        </tr>
                    <?php $i++;endforeach; ?>

                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php foreach($slides as $item):?>
        <!-- Modal Structure -->
        <div id="modal-<?php echo $item->id;?>" class="modal">
            <div class="modal-content">
                <h4>Attenzione</h4>
                <p class="flow-text">
                    Siete sicuri di eliminare il slide <b><?php echo $item->nome;?></b>
                    e tutte le immagini?
                </p>
            </div>
            <div class="modal-footer">

                <?php echo Html::link("slides/eliminare/" .
                    $slide->id, " Eliminare",
                    "class='btn red' title='Eliminare'");?>
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Annullare</a>
            </div>
        </div>
    <?php endforeach;?>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row"></div>
</div>
