<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 22/09/2016
 * Time: 07:12 PM
 */

?>
<div class="section scrollspy" id="servizi">
    <div class="container">
        <div class="row">
            <?php View::content() ?>
        </div>

        <div class="row">
            <blockquote>
                <h4>Modificare immagine</h4>
            </blockquote>
        </div>
        <div class="row">
            <?php echo Form::openMultipart() ?>
            <div class="col s12 m3 l3">
                <div class="card-panel center">

                    <?php echo Html::img("servizi/" . Utils::slug($servizio->nome) . "/" . $archivos->nombre, $archivos->nombre,
                        "class='materialboxed  responsive-img'"); ?>
                </div>
            </div>
            <div class="col s12 m9 l9">
                <div class="row">
                    <div class="input-field">
                        <?php echo Form::text("immagini_servizi.nome"); ?>
                        <label for="immagini_servizi_nome">Nome</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <?php echo Form::textarea("immagini_servizi.descrizione", "class='materialize-textarea'"); ?>
                        <label for="immagini_servizi_descrizione">Descrizione</label>
                    </div>
                </div>


            </div>


        </div>


        <div class="row center-align">
            <?php echo Html::link("immagini_servizi/mostrare/" . $servizio->id, "Annullare", "class=' btn-large btn-flat'"); ?>

            <?php echo Form::submit("Modificare", "class='waves-effect waves-light btn-block  
            btn-large yellow black-text'"); ?>
        </div>

        <?php echo Form::hidden("immagini_servizi.id", FALSE, $immagini_servizi->id); ?>
        <?php echo Form::hidden("immagini_servizi.files_id", FALSE, $archivos->id); ?>

        <?php echo Form::close(); ?>
    </div>
</div>
