<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 15/09/2016
 * Time: 02:07 PM
 */
View::content()
?>
<div class="section scrollspy" id="servizi">
    <div class="container">

        <div class="master">

            <div class="row">
                <h3 class=" ">I nostri servizi</h3>

            </div>

            <div class="row">

                <?php foreach ($servizi as $servizio): ?>
                    <div class=" col s12 m6 l6">

                        <div class="card  hoverable">
                            <div class=" card-image   ">
                                <?php $img_principale = $servizio->getImmaginePrincipale($servizio->id); ?>
                                <?php if ($img_principale->nombre != null): ?>
                                    <?php echo Html::img("servizi/" . Utils::slug($servizio->nome) . "/" . $img_principale->nombre
                                        , "", "class='  servizio center-align responsive-img'"); ?>
                                <?php else: ?>
                                    <?php echo Html::img("img-not-found.jpg", "", "class='servizio responsive-img'"); ?>
                                <?php endif; ?>
                            </div>
                            <div class="card-content black ">
                            <span class="card-title  white-text">
                                <?php echo $servizio->nome; ?>
                                 </span>
                                <a href="#" onclick="openDetails(<?php echo $servizio->id; ?>,event)"
                                   class="btn-floating waves-effect waves-light darken-1 yellow right">
                                    <i class="material-icons right">add</i>
                                </a>


                            </div>

                        </div>
                    </div>


                <?php endforeach; ?>


            </div>
        </div>

        <div class="row detail">


            <a id="btn-back" href="#" class="left hidden btn btn-floating blue"><i
                    class="material-icons" title="Ritorno">keyboard_backspace</i></a>

            <?php foreach ($servizi as $servizio): ?>
                <div class="hidden" id="detail-<?php echo $servizio->id; ?>">
                    <h4 class="center-align center"><?php echo $servizio->nome; ?></h4>

                    <p class="flow-text"><?php echo $servizio->descrizione; ?></p>
                    <?php if (strtolower($servizio->nome) == 'rivestimenti decorativi'): ?>
                        <h5>Dettaglio rivestimenti
                        </h5>
                    <?php else: ?>
                        <h5>Immagini</h5>
                    <?php endif; ?>
                    <?php foreach ($immagini = $servizio->getImmagini($servizio->id) as $item): ?>

                        <div class="col s12 m3 l3">
                            <div class="card-panel center">
                                <a rel="<?php echo $servizio->nome; ?>" class="swipebox" title="<?php echo
                                    '<b>' . $item->nome . '</b><br>' . $item->descrizione ?>"
                                   href="<?php echo PUBLIC_PATH . "img/servizi/" . Utils::slug($servizio->nome)
                                       . "/" . $item->nombre ?>">
                                    <?php echo Html::img("servizi/" . Utils::slug($servizio->nome) . "/" . $item->nombre
                                        , "", "class='  responsive-img'"); ?>

                                </a>

                            </div>
                            <?php if (strtolower($servizio->nome) == 'rivestimenti decorativi'): ?>
                                <div class="card-action center-align">
                                    <span><b><?php echo $item->nome; ?></b></span>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <input type="hidden" id="hdn_detail_id">
    </div>
</div>