<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 02/09/2016
 * Time: 07:32 PM
 */

?>
<!-- Contacto -->
<div class="section no-pad-bot scrollspy " id="contacto">
    <div class="container">
        <h3>
            Inviaci un messaggio</h3>


        <div class="row">
            <?php View::content(); ?>
        </div>
        <div class="row">
            <div id="resultado-contacto"></div>
        </div>
        <div class="row">

            <div class="col s12 m12 l12">
                <?php echo Ajax::form("resultado-contacto","contatto/enviar"); ?>
                <div class="row">

                    <div class="input-field col s12 m6 l6">
                        <i class="material-icons prefix">account_circle</i>
                        <?php echo Form::text("contacto.nombre", "id='nombre' class='validate' autofocus required", NULL); ?>
                        <label for="icon_prefix">Nome e cognome</label>
                    </div>
                    <div class="input-field col s12 m6 l6">
                        <i class="material-icons prefix">email</i>
                        <?php echo Form::email("contacto.email", "required id='email' class='validate'", NULL); ?>
                        <label data-error="Formato inválido" for="icon_email">E-mail</label>
                    </div>
                    <div class="input-field col s12 m12 l12">
                        <i class="material-icons prefix">mode_edit</i>
                        <?php echo Form::textarea("contacto.mensaje", "required id='mensaje' class='validate materialize-textarea'", NULL); ?>
                        <label for="mensaje">Messaggio</label>
                    </div>
                </div>
                <div class="row">
                    <div class="center-align">
                        <div data-callback="recaptchaCallback" name="captcha" class="g-recaptcha"
                             data-sitekey="6Lcg7AYUAAAAAEK-PUIs4wjbXhGLqWlQ6LhKTo-C"></div>
                    </div>
                </div>
                <div class="row">

                        <div class="center-align s12 m6 l6">

                            <?php echo Form::submit("Inviare",
                                "id='btn_submit' disabled class=' btn waves-effect waves-light btn-large light-green darken-1'"); ?>

                        </div>


                </div>

                <?php echo Form::close(); ?>


            </div>

        </div>

    </div>
</div>

<div class="row">

</div>
<div class="row">

</div>
<div class="row">

</div>