<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 28/08/2016
 * Time: 03:43 PM
 */

?>

<?php View::content(); ?>
<?php if (Router::get("controller") == "index" && Router::get("action") == "index"): ?>
    <footer class="page-footer  grey darken-4">

        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col s12 m12 l12">
                        <div class="left-align  col s3 m3 l3">

                            <b><?php echo date("Y") . " | " . Html::link("login", "PROPAINTER.IT", "class='white-text'"); ?> </b>


                        </div>

                        <div class="center-align col s6 m6 l6">
                            <b>Massimiliano Eduardo Saurin CF:SRNMSM79M01Z600O</b>
                        </div>
                        <div class="right-align col s3 m3 l3">

                            <a target="_blank" href="https://www.facebook.com/propainter.it"
                               class="btn-floating  waves-effect waves-light blue darken-1 tooltipped"
                               data-position="top" data-delay="50" data-tooltip="Diventare fan!">
                                <i class="fa fa-facebook"></i>
                            </a>

                            <a target="_blank" href="https://ar.linkedin.com/in/ezequiel-bär-coch-5478a263"
                               class="btn-floating  waves-effect waves-light grey lighten-3 tooltipped"
                               data-position="top" data-delay="50" data-tooltip="¿Piaciuto pagina? Contatto!">
                                <i class="material-icons black-text">code</i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

<?php else: ?>
    <!--Footer-->
    <footer class="page-footer  grey darken-4">
        <div class="container">
            <div class="row">
                <div class="col l6 m6 s12">
                    <div class="row">

                        <?php echo Html::img("logos/logo-min.png", "", "class='logo-footer responsive-img'"); ?>
                        <p class="white-text text-lighten-4"><i class="material-icons  tiny">phone</i>
                            +39.331.795.6936 &nbsp;&nbsp; <i class="material-icons  tiny">email</i>
                            info@propainter.it
                        </p>
                    </div>

                </div>


                <div class="col l4 offset-l2 s12">

                    <div class="row">
                        <div class="col s12 m12 l12">
                            <h5 class="white-text  left-align">Massimiliano Eduardo Saurin</h5>
                            <p class="white-text text-lighten-4">

                                P. IVA: 02460630037 <br>
                                PEC: propainter@legalmail.it<br>
                                CF: SRNMSM79M01Z600O
                            </p>


                        </div>



                        <!--                        <p class="white-text">Etichette</p>-->
                        <!--                        --><?php //foreach ($tags as $tag): ?>
                        <!---->
                        <!--                            <div class="chip">-->
                        <!--                                --><?php //echo $tag; ?>
                        <!---->
                        <!--                            </div>-->
                        <!--                        --><?php //endforeach; ?>
                    </div>


                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                <div class="row">


                    <div class="footer-copyright">
                    <div class="right">

                        <b><?php echo date("Y") ?> </b>&nbsp;&nbsp;

                        <a target="_blank" href="https://www.facebook.com/propainter.it"
                           class="btn-floating  waves-effect waves-light blue darken-1 tooltipped"
                           data-position="top" data-delay="50" data-tooltip="Diventare fan!">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a target="_blank" href="https://ar.linkedin.com/in/ezequiel-bär-coch-5478a263"
                           class="btn-floating  waves-effect waves-light grey lighten-3 tooltipped"
                           data-position="top" data-delay="50" data-tooltip="¿Ti é piaciuta la pagina? Contatto!">
                            <i class="material-icons black-text">code</i>
                        </a>
                    </div>
                    </div>
                </div>
            </div>
    </footer>

<?php endif; ?>
