<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 28/08/2016
 * Time: 03:43 PM
 */

?>

<?php View::content(); ?>
<?php if (Router::get("controller") == "index" && Router::get("action") == "index"): ?>
    <footer class="page-footer  grey darken-4">

        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col s12 m12 l12">
                        <div class="left-align  col s3 m3 l3">

                            <b><?php echo date("Y") . " | " . Html::link("login", "PROPAINTER.IT", "class='white-text'"); ?> </b>


                        </div>

                        <div class="center-align col s6 m6 l6">
                            <b><?php echo $utenti->nome . " " . $utenti->cognome; ?></b>
                        </div>
                        <div class="right-align col s3 m3 l3">

                            <a target="_blank" href="https://www.facebook.com/propainter.it"
                               class="btn-floating  waves-effect waves-light blue darken-1 tooltipped"
                               data-position="top" data-delay="50" data-tooltip="Diventare fan!">
                                <i class="fa fa-facebook"></i>
                            </a>

                            <a target="_blank" href="https://ar.linkedin.com/in/ezequiel-bär-coch-5478a263"
                               class="btn-floating  waves-effect waves-light grey lighten-3 tooltipped"
                               data-position="top" data-delay="50" data-tooltip="¿Piaciuto pagina? Contatto!">
                                <i class="material-icons black-text">code</i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

<?php else: ?>
    <!--Footer-->
    <footer class="page-footer  grey darken-4">
        <div class="container">
            <div class="row">
                <div class="col l6 m6 s12">
                    <div class="row">

                        <?php echo Html::img("logos/logo-min.png", "", "class='logo-footer responsive-img'"); ?>
                        <p class="white-text text-lighten-4"><i class="material-icons  tiny">phone</i>
                            <?php echo $utenti->telefono; ?> &nbsp;&nbsp; <i class="material-icons  tiny">email</i>
                            <?php echo $utenti->email_contatto; ?>
                        </p>
                    </div>

                </div>


                <div class="col l4 offset-l2 s12">

                    <div class="row">
                        <div class="col s12 m12 l12">
                            <h5 class="white-text  left-align"><?php echo $utenti->nome . " " . $utenti->cognome; ?></h5>
                            <p class="white-text text-lighten-4">

                                P. IVA: <?php echo $utenti->p_iva; ?> <br>
                                PEC: <?php echo $utenti->pec; ?><br>
                                CF: <?php echo $utenti->cf; ?>
                            </p>


                        </div>
                    </div>


                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                <div class="row">


                    <div class="footer-copyright">
                        <div class="right">

                            <b><?php echo date("Y") ?> </b>&nbsp;&nbsp;

                            <a target="_blank" href="<?php echo $utenti->facebook_url; ?>"
                               class="btn-floating  waves-effect waves-light blue darken-1 tooltipped"
                               data-position="top" data-delay="50" data-tooltip="Diventare fan!">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a target="_blank" href="https://ar.linkedin.com/in/ezequiel-bär-coch-5478a263"
                               class="btn-floating  waves-effect waves-light grey lighten-3 tooltipped"
                               data-position="top" data-delay="50" data-tooltip="¿Ti é piaciuta la pagina? Contatto!">
                                <i class="material-icons black-text">code</i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
    </footer>

<?php endif; ?>
