<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 16/09/2016
 * Time: 11:39 AM
 */
?>


<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
<meta name="theme-color" content="#000000">
<meta name="description"
      content="E un'impresa giovane, ma e anche il risultato di molti anni di esperienza nel campo delle vernici, delle
       decorazioni, della progettazione e realizzazione di stand e show-room.
Dedichiamo la massima attenzione ai dettagli, fin dai lavori più semplici a quelli più complessi. Non abbiamo fretta e
siamo soddisfatti solo quando ogni lavori si consegna al cliente al 100%
Comunque, garantendo gran professionalità e serietà nei lavori, sappiamo anche che riusciamo a offrire un rapporto
qualità prezzo molto vantaggioso, cercando sempre di adeguarci alle necessita e possibilità del cliente.
Ci accompagna la passione in quello che facciamo, per questo siamo orgogliosi della nostra impresa.">
<meta name="keywords"
      content="propainter,tingteggiature in generale,rivestimenti decorativi,pavimenti continui in resina,strutture in cartongesso,
      rimodellazioni,recupero e restauro strutture,patine,stucco veneziano,progettazione e allestimento stand e show-room">
<meta name="robots">
<title><?php echo $title." | ".Config::get("config.application.name");?></title>

<!-- CSS  -->
<?php Tag::css("plugin-min");?>
<?php Tag::css("custom-min");?>
<?php //Tag::css("material.min")?>

<?php Tag::css("estilos");?>
<script src='https://www.google.com/recaptcha/api.js?hl=it' async defer></script>
<link  href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="apple-touch-icon" sizes="57x57" href='/img/favicon/apple-icon-57x57.png'>
<link rel="apple-touch-icon" sizes="60x60" href='/img/favicon/apple-icon-60x60.png'>
<link rel="apple-touch-icon" sizes="72x72" href='/img/favicon/apple-icon-72x72.png'>
<link rel="apple-touch-icon" sizes="76x76" href='/img/favicon/apple-icon-76x76.png'>
<link rel="apple-touch-icon" sizes="114x114" href='/img/favicon/apple-icon-114x114.png'>
<link rel="apple-touch-icon" sizes="120x120" href='/img/favicon/apple-icon-120x120.png'>
<link rel="apple-touch-icon" sizes="144x144" href='/img/favicon/apple-icon-144x144.png'>
<link rel="apple-touch-icon" sizes="152x152" href='/img/favicon/apple-icon-152x152.png'>
<link rel="apple-touch-icon" sizes="180x180" href='/img/favicon/apple-icon-180x180.png'>
<link rel="icon" type="image/png" sizes="192x192"  href='/img/favicon/android-icon-192x192.png'>
<link rel="icon" type="image/png" sizes="32x32" href='/img/favicon/favicon-32x32.png'>
<link rel="icon" type="image/png" sizes="96x96" href='/img/favicon/favicon-96x96.png'>
<link rel="icon" type="image/png" sizes="16x16" href='/img/favicon/favicon-16x16.png'>
<link rel="manifest" href='/img/favicon/manifest.json'>
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/img/favicon/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">