<?php
/**
 * Created by PhpStorm.
 * User: Ezequiel
 * Date: 28/08/2016
 * Time: 03:44 PM
 */ ?>


<!--  Scripts-->

<?php //echo Tag::js('jquery/jquery.min'); ?>
<?php //echo Tag::js('jquery/jquery.kumbiaphp'); ?>
<?php //echo Tag::js('materialize.min');?>
<?php echo Tag::js("min/plugin-min"); ?>
<?php echo Tag::js("min/custom-min"); ?>
<?php echo Tag::js("jquery.swipebox.min");?>

<?php //echo Tag::js('material.min');?>

<script>
    PUBLIC_PATH = "<?php echo PUBLIC_PATH;?>";
</script>
<script>
    $(document).ready(function () {

        $('select').material_select();
        $( '.swipebox' ).swipebox();


    });

</script>
<?php if (Router::get("controller") == "index" && Router::get("action") == "index"): ?>
    <script>


        $(document).ready(function () {

            $('.tooltipped').tooltip({html: true});


            $('.slider').slider({full_width: true, indicators: false, interval: 7000, height: 815});


        });


    </script>

<?php endif; ?>


<?php if (in_array(Router::get("controller"), array("contatto"))): ?>
    <script>
        function recaptchaCallback() {
            $("#btn_submit").removeAttr("disabled");
        }
    </script>

<?php endif; ?>
<!---->
<?php //if (Router::get("action") == "nostri_lavori"): ?>
<!--    --><?php //echo Tag::js("isotope.pkgd.min"); ?>
<!--    <script>-->
<!---->
<!--        // portfolio filter-->
<!--        $(window).load(function () {-->
<!--            'use strict';-->
<!--            var galeria_selectores = $('.galeria-filter >a');-->
<!--            var galeria = $('.galeria-items');-->
<!--            galeria.isotope({-->
<!--                itemSelector: '.galeria-item',-->
<!--                layoutMode: 'masonry'-->
<!---->
<!--            });-->
<!---->
<!---->
<!--            galeria_selectores.on('click', function () {-->
<!--                $(this).siblings().addClass("btn-flat").removeClass("btn light-green darken-1");-->
<!--                $(this).addClass("btn light-green darken-1").removeClass("btn-flat ");-->
<!--                var selector = $(this).attr('data-filter');-->
<!--                galeria.isotope({filter: selector});-->
<!--                return false;-->
<!--            });-->
<!--        });-->
<!--        $('.materialboxed').materialbox();-->
<!--        //        Materialize.toast(' 650 m² cubiertos',4000);-->
<!--        //        Materialize.toast('  15 Consultorios',4200);-->
<!--        //        Materialize.toast('   2 aulas para integración escolar',4400);-->
<!--        //        Materialize.toast('  1 gimnasio totalmente equipado',4600);-->
<!--        //        Materialize.toast('1 sala de usos múltiples',4800);-->
<!--        //        Materialize.toast('   aire acondicionado y calefacción central',5000);-->
<!---->
<!---->
<!--    </script>-->
<?php //endif; ?>
<?php if (in_array(Router::get("controller"), array("immagini_servizi", "immagini_lavori"))): ?>
    <?php if (Router::get("action") == "mostrare"): ?>
        <script>
            $(document).ready(function () {
                //$('.modal-trigger').leanModal();
                $('.materialboxed').materialbox();
                function farePrincipale(e, img) {


                    e.preventDefault();

                    $.ajax({
                        url: PUBLIC_PATH + "immagini/fare_principale/" + img

                    }).done(function (data) {

                        $(document.body).find("#resultados").append(data);

                    });
                }
            });

        </script>

    <?php endif; ?>

<?php endif; ?>
<?php if (Router::get("controller") == "lavori" && in_array(Router::get("action"), array("aggiungere", "modificare"))): ?>
    <!--    --><?php //echo Tag::js("materialize.min"); ?>
    <script>
        //        var tags = [];
        //
        //        $(document).on("ready",function(){
        //            $('.chips-placeholder').material_chip({
        //                placeholder: 'Inserisci servizio',
        //                secondaryPlaceholder: '+Servizio',
        //
        //            });
        //
        //
        //            $('.chips').on('chip.add', function(e, chip){
        //                // you have the added chip here
        //                tags.push(chip.tag);
        //                $("#lavori_servizi_tags").val(tags);
        //            });
        //
        //        });
        //
        //
        //        $('.chips').on('chip.delete', function(e, chip){
        //            // you have the deleted chip here
        //            console.log(chip);
        //        });

    </script>
<?php endif; ?>
<?php if (in_array(Router::get("controller"), array("lavori", "servizis", "prodotti"))): ?>
    <?php if (Router::get("action") == "mostrare"): ?>
        <script>
            $(document).ready(function () {
                $('.modal-trigger').leanModal();
            });
        </script>
    <?php endif; ?>

    <?php if (Router::get("action") == "index"): ?>

        <script>
            $(document).ready(function () {
                //getServizi();
                $('.modal-trigger').leanModal();
                $('.materialboxed').materialbox();
                $("#btn-back").on("click", function (e) {


                    var detail_id = $("#hdn_detail_id").val();

                    $(".master").removeClass("hidden");
                    $("#detail-" + detail_id).addClass("hidden");
                    $("#btn-back").addClass("hidden");
                });
            });

            //            function getServizi(){
            //                //TODO:terminar esta función para cargar por AJAX los SERVIZIOS
            //                $.ajax({
            //                    url:PUBLIC_PATH+"servizi/index"
            //                }).done(function(data){
            //                    $.each(data,function(k,v){
            //                        var item ="";
            //                        item+="<div class='hidden' id='servizio-"+v.id+">";
            //                        item+="<h4>"+v.nome+"</h4>";
            //                        item+="<p class='flow-text'>"+ v.descrizione+"</p>";
            //                        $.each(v.id,function(){
            //                            item+=
            //                              $.ajax({
            //                                  url:PUBLIC_PATH+"servizi/getImmagini/"+v.id;
            //
            //                              }).done(function(data1){
            //                                  return data1;
            //                                });
            //
            //
            //                        });
            //                    });
            //
            //                });
            //            }


            function openDetails(detail_id, event) {

                $("#hdn_detail_id").val(detail_id);
                event.preventDefault();
                $(".master").addClass("hidden");
                $("#detail-" + detail_id).removeClass("hidden");
                $("#btn-back").removeClass("hidden");


            }
            $(function () {
                $.each($(".card-title"), function () {

                    if ($(this).html().length >= 40) {
                        $(this).css('font-size', '21px');
                    }
//                    else if{$(this).html().length >40}{
//                        $(this).css("font-size","14px");
//                    }

                });

            });


        </script>

    <?php endif; ?>
<?php endif; ?>
<?php if (in_array(Router::get("controller"), array("slides", "prodotti", "immagini_lavori", "immagini_servizi"))): ?>
    <?php if (Router::get("action") == "modificare"): ?>
        <script>
            $(document).ready(function () {
                $('.materialboxed').materialbox();
            });

        </script>
    <?php endif; ?>
    <?php if (Router::get("action") == "mostrare"): ?>
        <script>
            $(document).ready(function () {
                $('.modal-trigger').leanModal();
            });

        </script>
    <?php endif; ?>
    <?php if (Router::get("action") == "aggiungere"): ?>
        <script>
            $(function () {

                $("#img-preview").attr('src', PUBLIC_PATH +
                    '/img/img-not-found.jpg'
                );
                $("#file").change(function () {


                    checkExtension();
                    checkFileSize();
                    makePreview(this);


                });
            });
            function makePreview(input) {


                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $("#img-preview").attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }

            }

            function checkFileSize() {
                $.ajax({
                    url: PUBLIC_PATH + "admin/getMaxFileSize/" + $("input:file")[0].files[0].size
                }).done(function (data) {

                    if (data.length == 0) {
                        $("button:submit").attr("disabled", false);


                    }
                    else {
                        $("button:submit").attr("disabled", true);
                        $(".file-path").addClass("invalid").removeClass("valid");
                        $(document.body).find("#resultados").append(data);

                        setTimeout(function () {
                            $("#resultados").empty();

                        }, 3500);
                    }


                });
            }

            function checkExtension() {

                $.ajax({
                    url: PUBLIC_PATH + "admin/getFileType",
                    type: "post",
                    data: {fileType: $("input:file")[0].files[0].type}
                }).done(function (data) {
                    if (data.length == 0) {
                        $("button:submit").attr("disabled", false);
                        $(".file-path").addClass("valid").removeClass("invalid");
                    }
                    else {
                        $("button:submit").attr("disabled", true);
                        $(".file-path").addClass("invalid").removeClass("valid");
                        $(document.body).find("#resultados").append(data);

                        setTimeout(function () {
                            $("#resultados").empty();

                        }, 3500);
                    }

                });
            }
        </script>
    <?php endif; ?>
<?php endif; ?>

<?php if (Router::get("controller") == "utenti" && Router::get("action") == "modificare"): ?>
    <?php echo Tag::js("utenti/aggiornare"); ?>
<?php endif; ?>
